version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - cd application
      - sam build
      - sam deploy --stack-name fcfunck-demo-rag --no-confirm-changeset --no-fail-on-empty-changeset --resolve-s3 --capabilities CAPABILITY_IAM